.TH "Component" 3 "21 Mar 2009" "Version 0.1" "m4php5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Component \- 
.SH SYNOPSIS
.br
.PP
Inherits Dispatcher.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($module, $action='index', $params=null)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBComponent\fP class, allows a component to be inserted into a template, including controller logic. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Component::__construct ($ module, $ action = \fC'index'\fP, $ params = \fCnull\fP)"
.PP
Constructor
.PP
\fBParameters:\fP
.RS 4
\fI$module\fP Module to display 
.br
\fI$action\fP Content to display 
.br
\fI$params\fP Modules parameters 
.RE
.PP
\fBReturns:\fP
.RS 4
Display 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for m4php5 from the source code.
