.TH "Config" 3 "21 Mar 2009" "Version 0.1" "m4php5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Config \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBload\fP ($array)"
.br
.ti -1c
.RI "static \fBgetAlternateLangs\fP ()"
.br
.ti -1c
.RI "static \fBgetAllLangs\fP ()"
.br
.ti -1c
.RI "static \fBget\fP ($var)"
.br
.ti -1c
.RI "static \fBset\fP ($var, $val)"
.br
.ti -1c
.RI "static \fBgetPref\fP ($var)"
.br
.ti -1c
.RI "static \fBarrayize\fP (&$item, $key)"
.br
.ti -1c
.RI "static \fBsetPref\fP ($var, $val)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Global configuration helper Store and retrieve configuration options accross application 
.SH "Member Function Documentation"
.PP 
.SS "static Config::load ($ array)\fC [static]\fP"
.PP
Load configuration
.PP
public 
.PP
\fBParameters:\fP
.RS 4
\fIarray\fP $array ?? 
.RE
.PP

.SS "static Config::getAlternateLangs ()\fC [static]\fP"
.PP
Get Alternate Languages
.PP
public 
.SS "static Config::getAllLangs ()\fC [static]\fP"
.PP
Get all language
.PP
public 
.PP
\fBReturns:\fP
.RS 4
?? ?? 
.RE
.PP

.SS "static Config::get ($ var)\fC [static]\fP"
.PP
Get config value
.PP
public 
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP $var Variable to get 
.RE
.PP
\fBReturns:\fP
.RS 4
string Value 
.RE
.PP

.SS "static Config::set ($ var, $ val)\fC [static]\fP"
.PP
Set config value
.PP
public 
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP $var Variable to set 
.br
\fIstring\fP $val Value 
.RE
.PP

.SS "static Config::getPref ($ var)\fC [static]\fP"
.PP
Get preferences value
.PP
public 
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP $var Variable to get 
.RE
.PP
\fBReturns:\fP
.RS 4
string Value 
.RE
.PP

.SS "static Config::arrayize (&$ item, $ key)\fC [static]\fP"
.PP
??
.PP
public 
.PP
\fBParameters:\fP
.RS 4
\fI??\fP $item ?? 
.br
\fI??\fP $key ?? 
.RE
.PP
\fBReturns:\fP
.RS 4
?? Value 
.RE
.PP

.SS "static Config::setPref ($ var, $ val)\fC [static]\fP"
.PP
Set preferences values
.PP
public 
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP $var Variable to set 
.br
\fIstring\fP $val Value 
.RE
.PP
\fBReturns:\fP
.RS 4
string Value 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for m4php5 from the source code.
