.TH "cssmin" 3 "22 Mar 2009" "Version 0.1" "m4php5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cssmin \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
cssmin.php - A simple CSS minifier. --
.PP
\fC include('cssmin.php'); file_put_contents('path/to/target.css', cssmin::minify(file_get_contents('path/to/source.css'))); \fP --
.PP
THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. --
.PP
\fBAuthor:\fP
.RS 4
Joe Scylla <joe.scylla@gmail.com>  2008 Joe Scylla <joe.scylla@gmail.com>  http://opensource.org/licenses/mit-license.php MIT License 
.RE
.PP
\fBVersion:\fP
.RS 4
1.0.1.b3 (2008-10-02) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for m4php5 from the source code.
