.TH "DataObjects_Album_i18n" 3 "22 Mar 2009" "Version 0.1" "m4php5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataObjects_Album_i18n \- 
.SH SYNOPSIS
.br
.PP
Inherits DB_DataObject_Pluggable.
.PP
.SH "Detailed Description"
.PP 
Table Definition for album_i18n 

.SH "Author"
.PP 
Generated automatically by Doxygen for m4php5 from the source code.
