.TH "DataObjects_Notmigrated_withspecialnames" 3 "22 Mar 2009" "Version 0.1" "m4php5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataObjects_Notmigrated_withspecialnames \- 
.SH SYNOPSIS
.br
.PP
Inherits DB_DataObject_Pluggable.
.PP
.SH "Detailed Description"
.PP 
Table Definition for notmigrated_withspecialnames 

.SH "Author"
.PP 
Generated automatically by Doxygen for m4php5 from the source code.
