.TH "DataObjects_Vanillainnodb" 3 "21 Mar 2009" "Version 0.1" "m4php5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataObjects_Vanillainnodb \- 
.SH SYNOPSIS
.br
.PP
Inherits DB_DataObject_Pluggable.
.PP
.SH "Detailed Description"
.PP 
Table Definition for vanillainnodb 

.SH "Author"
.PP 
Generated automatically by Doxygen for m4php5 from the source code.
