.TH "Dispatcher" 3 "22 Mar 2009" "Version 0.1" "m4php5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dispatcher \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBMaman\fP.
.PP
Inherited by \fBComponent\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($module= 'defaut', $action= 'index', $params=null)"
.br
.ti -1c
.RI "\fBexecute\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "& \fBgetPage\fP ()"
.br
.ti -1c
.RI "\fBgetPath\fP ()"
.br
.ti -1c
.RI "\fBdisplay\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBDispatcher\fP Class The main and only goal of the dispatcher is to route the request to the correct \fBModule\fP The constructor takes two parameters, 1 and 2 correspond to the module and action names. The third one is optional parameters to pass to module. Mostly used when a module is used as a component 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Dispatcher::__construct ($ module = \fC'defaut'\fP, $ action = \fC'index'\fP, $ params = \fCnull\fP)"
.PP
Constructor
.PP
\fBParameters:\fP
.RS 4
\fI$module\fP \fBModule\fP to dispatch 
.br
\fI$action\fP Action to dispatch 
.br
\fI$params\fP Optional parameters 
.RE
.PP

.PP
Reimplemented in \fBComponent\fP.
.SH "Member Function Documentation"
.PP 
.SS "Dispatcher::execute ()"
.PP
Execute the dispatch
.PP
public 
.SS "& Dispatcher::getPage ()\fC [static]\fP"
.PP
Get the module page
.PP
public 
.PP
\fBReturns:\fP
.RS 4
string \fBModule\fP page 
.RE
.PP

.SS "Dispatcher::getPath ()\fC [static]\fP"
.PP
Get the module path
.PP
public 
.PP
\fBReturns:\fP
.RS 4
string \fBModule\fP path 
.RE
.PP

.SS "Dispatcher::display ()\fC [static]\fP"
.PP
Display the module
.PP
public 
.PP
\fBReturns:\fP
.RS 4
string \fBModule\fP output 
.RE
.PP

.PP
Reimplemented in \fBComponent\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for m4php5 from the source code.
