.TH "iSetup" 3 "22 Mar 2009" "Version 0.1" "m4php5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iSetup \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Simple application setup interface Used to 'boot' the current application e.g. fill the configuration values (Database and other stuff needed at startup) 

.SH "Author"
.PP 
Generated automatically by Doxygen for m4php5 from the source code.
