.TH "Joomla::Framework" 3 "20 Mar 2009" "Version 0.1" "m4php5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Joomla::Framework \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Base class for a Joomla! application.
.PP
Acts as a Factory class for application specific objects and provides many supporting API functions. Derived clases should supply the route(), dispatch() and render() functions.
.PP
Application 
.PP
\fBSince:\fP
.RS 4
1.5 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for m4php5 from the source code.
