.TH "Log" 3 "22 Mar 2009" "Version 0.1" "m4php5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Log \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBinfo\fP ($message)"
.br
.ti -1c
.RI "static \fBmessage\fP ($message, $level=Log::LOGLEVEL_INFO)"
.br
.ti -1c
.RI "static \fBmail\fP ($message)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Very basic log class 
.SH "Member Function Documentation"
.PP 
.SS "static Log::info ($ message)\fC [static]\fP"
.PP
Info
.PP
public 
.SS "static Log::message ($ message, $ level = \fCLog::LOGLEVEL_INFO\fP)\fC [static]\fP"
.PP
Write message to log file
.PP
public 
.SS "static Log::mail ($ message)\fC [static]\fP"
.PP
\fBMail\fP message
.PP
public 

.SH "Author"
.PP 
Generated automatically by Doxygen for m4php5 from the source code.
