.TH "M_Crypt" 3 "22 Mar 2009" "Version 0.1" "m4php5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
M_Crypt \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBencrypt\fP ($val, $ky=null)"
.br
.ti -1c
.RI "static \fBdecrypt\fP ($val, $ky=null)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Strong encryption/decryption static methods Dependency : PEAR_Crypt_Blowfish 
.SH "Member Function Documentation"
.PP 
.SS "static M_Crypt::encrypt ($ val, $ ky = \fCnull\fP)\fC [static]\fP"
.PP
Encrypt data
.PP
public
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP $val Data to encrypt 
.br
\fIstring\fP $ky Key 
.RE
.PP
\fBReturns:\fP
.RS 4
string Encrypted data 
.RE
.PP

.SS "static M_Crypt::decrypt ($ val, $ ky = \fCnull\fP)\fC [static]\fP"
.PP
Encrypt data
.PP
public
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP $val Data to encrypt 
.br
\fIstring\fP $ky Key 
.RE
.PP
\fBReturns:\fP
.RS 4
string Encrypted data 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for m4php5 from the source code.
