.TH "M_Crypt" 3 "21 Mar 2009" "Version 0.1" "m4php5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
M_Crypt \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Strong encryption/decryption static methods Dependency : PEAR_Crypt_Blowfish 

.SH "Author"
.PP 
Generated automatically by Doxygen for m4php5 from the source code.
