.TH "M_Office" 3 "22 Mar 2009" "Version 0.1" "m4php5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
M_Office \- 
.SH SYNOPSIS
.br
.PP
Inherits M_Office_Controller.
.PP
.SH "Detailed Description"
.PP 
'Office' application dispatcher The office application is one of the most powerful features of the \fBM\fP framework. It's also the one that needs most refactoring This was originally base upon Justin Patrin's PEAR_DB_DataObject_FormBuilder_Frontend 

.SH "Author"
.PP 
Generated automatically by Doxygen for m4php5 from the source code.
