.TH "Mail" 3 "22 Mar 2009" "Version 0.1" "m4php5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mail \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBMaman\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($config)"
.br
.ti -1c
.RI "\fBaddFile\fP ($filepath)"
.br
.ti -1c
.RI "\fBsetVars\fP ($vars)"
.br
.ti -1c
.RI "\fBassign\fP ($var, $val)"
.br
.ti -1c
.RI "\fBappend\fP ($var, $val)"
.br
.ti -1c
.RI "\fBsetTemplate\fP ($tpl)"
.br
.ti -1c
.RI "\fBsendToAdmin\fP ()"
.br
.ti -1c
.RI "\fBgetSubject\fP ()"
.br
.ti -1c
.RI "\fBgetAltbody\fP ()"
.br
.ti -1c
.RI "\fBgetBody\fP ()"
.br
.ti -1c
.RI "\fBfetch\fP ()"
.br
.ti -1c
.RI "\fBsendTo\fP ($mail)"
.br
.ti -1c
.RI "\fBrawsend\fP ($from, $to, $subject, $htmlbody, $altbody=null, $options=null, $attachments=null, $html=false)"
.br
.ti -1c
.RI "\fBgetContents\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static & \fBfactory\fP ($template)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBMail\fP class. Holds an \fBMtpl\fP object so mails can be handled just like \fBModule\fP templates Sent mails can be stored as log files (or not), mailed (or not), and also mailed to only one static recipient (for testing purpose) depending on the configuration options setup in the PEAR::getStaticProperty('Mail','global') 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Mail::__construct ($ config)"
.PP
Constructor
.PP
\fBParameters:\fP
.RS 4
\fI$config\fP string Template config 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "Mail::addFile ($ filepath)"
.PP
Attach files
.PP
public 
.PP
\fBParameters:\fP
.RS 4
\fI$filepath\fP string Path to file 
.RE
.PP

.SS "Mail::setVars ($ vars)"
.PP
Set mail vars
.PP
\fBParameters:\fP
.RS 4
\fI$vars\fP 
.RE
.PP

.SS "Mail::assign ($ var, $ val)"
.PP
Assign mail vars
.PP
public 
.PP
\fBParameters:\fP
.RS 4
\fI$var\fP string Var 
.br
\fI$val\fP string Value 
.RE
.PP

.SS "Mail::append ($ var, $ val)"
.PP
Append mail vars
.PP
public 
.PP
\fBParameters:\fP
.RS 4
\fI$var\fP string Var 
.br
\fI$val\fP string Value 
.RE
.PP

.SS "Mail::setTemplate ($ tpl)"
.PP
Set mail template
.PP
\fBParameters:\fP
.RS 4
\fI$tpl\fP string Template 
.RE
.PP

.SS "static& Mail::factory ($ template)\fC [static]\fP"
.PP
Email creation
.PP
public
.PP
\fBParameters:\fP
.RS 4
\fI$template\fP string Template 
.RE
.PP
\fBReturns:\fP
.RS 4
Email class 
.RE
.PP

.SS "Mail::sendToAdmin ()"
.PP
\fBMail\fP send to admin
.PP
public 
.SS "Mail::getSubject ()"
.PP
Get mail subject
.PP
public 
.PP
\fBReturns:\fP
.RS 4
Subject string 
.RE
.PP

.SS "Mail::getAltbody ()"
.PP
Get Alternate body
.PP
public 
.PP
\fBReturns:\fP
.RS 4
Body string 
.RE
.PP

.SS "Mail::getBody ()"
.PP
Get body
.PP
public 
.PP
\fBReturns:\fP
.RS 4
Body string 
.RE
.PP

.SS "Mail::fetch ()"
.PP
Fetch template
.PP
public 
.SS "Mail::sendTo ($ mail)"
.PP
Send to vars
.PP
public 
.PP
\fBParameters:\fP
.RS 4
\fI$mail\fP 
.RE
.PP

.SS "Mail::rawsend ($ from, $ to, $ subject, $ htmlbody, $ altbody = \fCnull\fP, $ options = \fCnull\fP, $ attachments = \fCnull\fP, $ html = \fCfalse\fP)"
.PP
Raw Send \fBMail\fP
.PP
public 
.PP
\fBParameters:\fP
.RS 4
\fI$from\fP string From 
.br
\fI$to\fP string To 
.br
\fI$subject\fP string Subject 
.br
\fI$htmlbody\fP string HTML Body 
.br
\fI$altbody\fP string Alternate body 
.br
\fI$options\fP array Options 
.br
\fI$attachments\fP array Attachments 
.br
\fI$html\fP boolean Is HTML 
.RE
.PP

.SS "Mail::getContents ()"
.PP
Get mail contents
.PP
public 
.PP
\fBReturns:\fP
.RS 4
Content 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for m4php5 from the source code.
