.TH "MArray" 3 "22 Mar 2009" "Version 0.1" "m4php5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MArray \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBarray_merge_recursive_unique\fP ($first, $second, $greedy=false)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Static class providing array related helper methods 
.SH "Member Function Documentation"
.PP 
.SS "static MArray::array_merge_recursive_unique ($ first, $ second, $ greedy = \fCfalse\fP)\fC [static]\fP"
.PP
Merge array
.PP
public 
.PP
\fBReturns:\fP
.RS 4
Merged array array 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for m4php5 from the source code.
