.TH "MGeo" 3 "22 Mar 2009" "Version 0.1" "m4php5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MGeo \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Helper class to work with google maps geocoding API Also provides helper methods for satellite settings (azimut - elevation - polarity) 

.SH "Author"
.PP 
Generated automatically by Doxygen for m4php5 from the source code.
