.TH "Module_Unittests" 3 "21 Mar 2009" "Version 0.1" "m4php5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Module_Unittests \- 
.SH SYNOPSIS
.br
.PP
Inherits Module.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdoExecLaunchnodb\fP ()"
.br
.ti -1c
.RI "\fBdoExecLaunchdb\fP ()"
.br
.ti -1c
.RI "\fBdoExecInitFrameworkDOs\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Module_Unisttests 
.SH "Member Function Documentation"
.PP 
.SS "Module_Unittests::doExecLaunchnodb ()"
.PP
Launches tests with no db alteration 
.SS "Module_Unittests::doExecLaunchdb ()"
.PP
Launches tests with no db alteration 
.SS "Module_Unittests::doExecInitFrameworkDOs ()"
.PP
Used for framework tests development 

.SH "Author"
.PP 
Generated automatically by Doxygen for m4php5 from the source code.
