.TH "MPdf" 3 "22 Mar 2009" "Version 0.1" "m4php5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MPdf \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBMaman\fP.
.PP
.SH "Detailed Description"
.PP 
PDF generation class using dompdf external library and \fBMtpl\fP as the template engine 

.SH "Author"
.PP 
Generated automatically by Doxygen for m4php5 from the source code.
