.TH "Mreg" 3 "22 Mar 2009" "Version 0.1" "m4php5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mreg \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static & \fBget\fP ($key)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a registry class 
.PP
\fBSee also:\fP
.RS 4
registry design pattern 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static& Mreg::get ($ key)\fC [static]\fP"
.PP
Restaure un objet enregistré
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP $key 
.RE
.PP
\fBReturns:\fP
.RS 4
objet 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for m4php5 from the source code.
