.TH "Notifier" 3 "22 Mar 2009" "Version 0.1" "m4php5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Notifier \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBNotifier\fP class which goal is to send and receive messages from other objects 
.PP
\fBSee also:\fP
.RS 4
observable pattern 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for m4php5 from the source code.
