.TH "Payment" 3 "22 Mar 2009" "Version 0.1" "m4php5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Payment \- 
.SH SYNOPSIS
.br
.PP
Inherited by Payment_Driver_SIPS.
.PP
.SH "Detailed Description"
.PP 
Credit card payment process abstraction - draft (currently includes a driver for ATOS SIPS) 

.SH "Author"
.PP 
Generated automatically by Doxygen for m4php5 from the source code.
