.TH "PHPMailer" 3 "21 Mar 2009" "Version 0.1" "m4php5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHPMailer \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
PHPMailer language file. Italian version
.PP
\fBAuthor:\fP
.RS 4
Ilias Bartolini <brain79@inwind.it>
.RE
.PP
PHPMailer language file. Romanian Version
.PP
\fBAuthor:\fP
.RS 4
Catalin Constantin <catalin@dazoot.ro> 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for m4php5 from the source code.
