.TH "T" 3 "22 Mar 2009" "Version 0.1" "m4php5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
T \- 
.SH SYNOPSIS
.br
.PP
Inherited by T_editor, and T_reader.
.PP
.SH "Detailed Description"
.PP 
Translation class for static strings be aware that this file also provides the __() as _e() functions ! 

.SH "Author"
.PP 
Generated automatically by Doxygen for m4php5 from the source code.
