.TH "URL" 3 "22 Mar 2009" "Version 0.1" "m4php5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
URL \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Url generation class. Includes 'old' and 'new' flavour the new flavour uses PEAR Net_URL_Mapper and is more powerful. But not used in production yet... 'old' flavour simply creates a module/action then appends the other passed variables as a query string 

.SH "Author"
.PP 
Generated automatically by Doxygen for m4php5 from the source code.
